Add DeleteObjectSetFromDeviceRpc.
frugalos/libfrugalos pull request #3
Opened 2018-11-20 06:00 UTC by shinnya

I've added a new rpc for deleting objects from a device.

2018-11-20 06:06 UTC, shinnya commented on src/entity/object.rs
> +impl FromStr for ObjectVersion {
Used when parsing a command-line option.

2018-11-20 06:06 UTC, shinnya commented on src/client/frugalos.rs
> +    ) -> impl Future<Item = (), Error = Error> {
`DeviceId` is required here because we delete objects from a specific device.

2018-11-20 06:06 UTC, shinnya commented on src/client/frugalos.rs
> +        object_ids: BTreeSet<ObjectId>,
Use `BTreeSet` because we'd like to remove duplicated objects for efficiency.

2018-11-24 09:06 UTC, sile requested changes

2018-11-24 09:06 UTC, sile commented on src/entity/object.rs
> +                .map(|n| ObjectVersion(n))
`clippy` warns this line ( https://travis-ci.org/frugalos/libfrugalos/jobs/457307395#L576 ).

2018-11-24 09:06 UTC, sile commented on src/entity/device.rs
> +/// the sequence number of devices, which is increased monotonically.
A sentence should start with an upper case character.
See also: https://doc.rust-lang.org/1.0.0/style/style/comments.html#sentence-structure

2018-11-24 09:06 UTC, sile commented on src/schema/frugalos.rs
> +/// A RPC for deleting objects physically.
Perhaps, "An" is correct for "RPC".

2018-11-24 09:06 UTC, sile commented on src/schema/frugalos.rs
> +    /// a bucket which owns the objects
See: https://doc.rust-lang.org/1.0.0/style/style/comments.html#sentence-structure

2018-11-26 22:34 UTC, shinnya commented on src/entity/object.rs
> +                .map(|n| ObjectVersion(n))
fixed

2018-11-27 03:40 UTC, sile approved these changes
LGTM

2018-11-27 08:08 UTC, merged